app/blueprints/products.py
from flask import Blueprint, render_template, request, url_for, flash
from flask_login import login_required, current_user
from werkzeug.exceptions import abort
from werkzeug.utils import redirect

from app.extensions import db, checkout
from app.forms import ProductForm
from app.models import Product

products = Blueprint('products', __name__)


@products.route('/')
def index():
    all_products = Product.query.all()
    return render_template('products/index.html', products=all_products)


@products.route('/<int:product_id>')
def details(product_id):
    product = Product.query.get_or_404(product_id)

    stripe_publishable_key = checkout.publishable_key
    stripe_session = checkout.create_session(product) or {}
    checkout_session_id = stripe_session.get('id')

    return render_template('products/details.html',
                           product=product,
                           stripe_publishable_key=stripe_publishable_key,
                           checkout_session_id=checkout_session_id)


@products.route('/<product_id>/post-checkout')
def post_checkout(product_id):
    product = Product.query.get_or_404(product_id)
    purchase_state = request.args.get('status')
    post_purchase_session_id = request.args.get('session_id')

    if purchase_state == 'success' and post_purchase_session_id:
        flash("Thanks for purchasing {}. You will receive an email shortly".format(product.name), 'success')
    elif purchase_state == 'cancel' and post_purchase_session_id:
        flash("There was an error while attempting to purchase this product. Try again", 'danger')

    return redirect(url_for('products.details', product_id=product_id))


@products.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = ProductForm()
    if form.validate_on_submit():
        price = form.price.data or 0
        product = Product(name=form.name.data,
                          description=form.description.data,
                          price_cents=int(price*100),
                          picture_url=form.picture_url.data,
                          creator=current_user,
                          store=current_user.store)
        db.session.add(product)
        db.session.commit()

        return redirect(url_for('products.details', product_id=product.id))
    return render_template('products/create.html', form=form)


@products.route('/<product_id>/edit', methods=['GET', 'POST'])
@login_required
def edit(product_id):
    product = Product.query.get_or_404(product_id)
    form = ProductForm(obj=product)
    if form.validate_on_submit():
        product.name = form.name.data
        product.description = form.description.data
        db.session.add(product)
        db.session.commit()
        return redirect(url_for('.details', product_id=product.id))
    return render_template('products/edit.html', form=form, product=product)

app/blueprints/stores.py
from flask import Blueprint, render_template

from app.models import Store, Product

store_bp = Blueprint('store', __name__)


@store_bp.route('/stores')
def index():
    stores = Store.query.all()
    return render_template('stores/index.html', stores=stores)


@store_bp.route('/stores/<store_id>')
@store_bp.route('/stores/<store_id>/<int:page>')
def show(store_id, page=1):
    store = Store.query.get_or_404(store_id)
    per_page = 9
    products_pagination = Product.query.filter_by(store=store).paginate(page, per_page)
    return render_template('stores/show.html', store=store, products_pagination=products_pagination)

app/templates/products/create.html
{% from "_formhelpers.html" import render_field %}

{% extends "base_layout.html" %}

{% block title %} New Product {% endblock %}

{% block content %}
<form method="POST" action="{{ url_for('products.create') }}">
    {{ form.csrf_token }}
    {{ render_field(form.name) }}
    {{ render_field(form.description) }}
    {{ render_field(form.price, placeholder="5.00") }}
    {{ render_field(form.picture_url, placeholder="https://example.com/image.png") }}

    <button type="submit" class="btn btn-primary">Create</button>
</form>
{% endblock %}

app/templates/products/details.html
{% extends "base_layout.html" %}

{% block custom_assets %}
<script type="text/javascript" src="https://js.stripe.com/v3/"></script>

<script>
var stripe = Stripe('{{ stripe_publishable_key }}');
</script>

{% assets "checkout_js" %}
<script type="text/javascript" src="{{ ASSET_URL }}"> </script>
{% endassets %}
{% endblock %}


{% block content %}
<div class="container">
    <div class="row mb-2">
      <div class="col col-12 col-sm-6">
        <img src="{{ product.primary_image_url }}" alt="Product Image" class="img-fluid img-thumbnail" />
      </div>
      <div class="col col-12 col-sm-6">
        <h1> {{ product.name }} </h1>
        <hr />
        {% if checkout_session_id %}
          <button onclick="purchase(stripe, '{{ checkout_session_id }}')" class="btn btn-primary"> Buy for {{ "${:,.2f}".format(product.price_cents/100.0) }} </button>
          <hr />
        {% else %}
          Sold out
        {% endif %}
        <span> {{ product.description }} </span>
        <hr />
        <a href="{{ url_for('store.show', store_id=product.store.id) }}" class="btn btn-secondary btn-sm">
          See more products from {{ product.store.name }} </a>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/products/edit.html
{% from "_formhelpers.html" import render_field %}

{% extends "base_layout.html" %}

{% block title %} Edit {{ product.name }} {% endblock %}

{% block content %}
<div class="container">
    <form method="POST" action="{{ url_for('products.edit', product_id=product.id) }}">
    {{ render_field(form.name) }}
    {{ render_field(form.description) }}
    <button type="submit" class="btn btn-primary">Edit</button>
    </form>
</div>
{% endblock %}

app/templates/products/index.html
{% extends "base_layout.html" %}

{% block title %} All Products {% endblock %}

{% block content %}
  <div class="container">
    <table class="table">
        <thead>
          <tr>
            <th scope="col">Product</th>
            <th scope="col">Name</th>
            <th scope="col">Store</th>
            <th scope="col">Description</th>
          </tr>
        </thead>
        <tbody>
          {% for product in products %}
            <tr>
              <th scope="row">
                <img src="{{ product.primary_image_url }}" alt="Product Image" width="50px" class="img-thumbnail" />
              </th>
              <th scope="row">
                <a href="{{ url_for('products.details', product_id=product.id) }}">
                    {{ product.name }}
                </a>
              </th>
              <th scope="row">
                {% if product.store_id %}
                  <a href="{{ url_for('store.show', store_id=product.store_id) }}" class="card-link btn btn-outline-primary">
                      {{ product.store.name }}
                  </a>
                {% endif %}
              </th>
              <th scope="row">{{ product.description }}</th>
            </tr>
        {% endfor %}
        </tbody>
    </table>
  </div>
{% endblock %}

app/templates/products/new_plain_form.html
{% extends "base_layout.html" %}

{% block title %} New Product {% endblock %}

{% block content %}
<div class="container">
    <form method="POST">
        <label for="name">Name</label>
        <input type="text" class="form-control" name="name" />
        <label for="description">Description</label>
        <input type="textarea" class="form-control" name="description" />
        <br />
        <input type="submit" class="btn btn-primary"/>
    </form>
</div>
{% endblock %}