app/blueprints/landing.py
from flask import Blueprint, render_template
import logging

from flask_login import current_user
from sqlalchemy.orm import joinedload

from app.extensions import cache
from app.models import Store

logger = logging.getLogger(__name__)

landing_bp = Blueprint('landing', __name__)


@landing_bp.route('/')
@cache.cached(timeout=60, unless=lambda: current_user.is_authenticated)
def index():
    # This is a bad query, we'll optimize it later
    stores = Store.query.options(
        joinedload(Store.products)
    ).limit(3).all()
    return render_template('landing/index.html', stores=stores)


@landing_bp.route('/error')
def error():
    logger.warning("About to do a dangerous calculation", extra={'data': 1})
    1/0

app/blueprints/products.py
from flask import Blueprint, render_template, request, url_for, flash
from flask_login import login_required, current_user
from werkzeug.exceptions import abort
from werkzeug.utils import redirect

from app.extensions import db, checkout
from app.forms import ProductForm
from app.models import Product

products = Blueprint('products', __name__)


@products.route('/')
def index():
    all_products = Product.query.all()
    return render_template('products/index.html', products=all_products)


@products.route('/<int:product_id>')
def details(product_id):
    product = Product.query.get_or_404(product_id)

    stripe_publishable_key = checkout.publishable_key
    stripe_session = checkout.create_session(product) or {}
    checkout_session_id = stripe_session.get('id')

    return render_template('products/details.html',
                           product=product,
                           stripe_publishable_key=stripe_publishable_key,
                           checkout_session_id=checkout_session_id)


@products.route('/<product_id>/post-checkout')
def post_checkout(product_id):
    product = Product.query.get_or_404(product_id)
    purchase_state = request.args.get('status')
    post_purchase_session_id = request.args.get('session_id')

    if purchase_state == 'success' and post_purchase_session_id:
        flash("Thanks for purchasing {}. You will receive an email shortly".format(product.name), 'success')
    elif purchase_state == 'cancel' and post_purchase_session_id:
        flash("There was an error while attempting to purchase this product. Try again", 'danger')

    return redirect(url_for('products.details', product_id=product_id))


@products.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = ProductForm()
    if form.validate_on_submit():
        price = form.price.data or 0
        product = Product(name=form.name.data,
                          description=form.description.data,
                          price_cents=int(price*100),
                          picture_url=form.picture_url.data,
                          creator=current_user,
                          store=current_user.store)
        db.session.add(product)
        db.session.commit()

        return redirect(url_for('products.details', product_id=product.id))
    return render_template('products/create.html', form=form)


@products.route('/<product_id>/edit', methods=['GET', 'POST'])
@login_required
def edit(product_id):
    product = Product.query.get_or_404(product_id)
    form = ProductForm(obj=product)
    if form.validate_on_submit():
        product.name = form.name.data
        product.description = form.description.data
        db.session.add(product)
        db.session.commit()
        return redirect(url_for('.details', product_id=product.id))
    return render_template('products/edit.html', form=form, product=product)

app/blueprints/stores.py
from flask import Blueprint, render_template

from app.models import Store, Product

store_bp = Blueprint('store', __name__)


@store_bp.route('/stores')
def index():
    stores = Store.query.all()
    return render_template('stores/index.html', stores=stores)


@store_bp.route('/stores/<store_id>')
@store_bp.route('/stores/<store_id>/<int:page>')
def show(store_id, page=1):
    store = Store.query.get_or_404(store_id)
    per_page = 9
    products_pagination = Product.query.filter_by(store=store).paginate(page, per_page)
    return render_template('stores/show.html', store=store, products_pagination=products_pagination)

app/blueprints/users.py
from flask import Blueprint, render_template, redirect, url_for, flash, session, request
from flask_login import login_user, login_required, logout_user, current_user

from app.email import send_pretty_welcome_message
from app.extensions import login_manager
from app.models import User, db, Store
from app.forms import SignupForm, LoginForm

user_bp = Blueprint('user', __name__)


@user_bp.route('/register', methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        flash("You are already logged in", 'warning')
        return redirect(url_for("products.index"))

    form = SignupForm()
    if form.validate_on_submit():
        user = User.create(form.email.data, form.password.data)
        store = Store(name=form.store_name.data, user=user)
        db.session.add(store)
        db.session.commit()

        login_user(user)
        send_pretty_welcome_message(user)

        flash("Registered succesfully.", "success")
        return redirect(session.get('after_login') or url_for("products.index"))
    return render_template("users/register.html", form=form)


@user_bp.route('/login', methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        flash("You are already logged in", 'warning')
        return redirect(url_for("products.index"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        login_user(user)
        flash("Logged in successfully.", "success")
        return redirect(url_for("products.index"))

    return render_template("users/login.html", form=form)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


@login_manager.unauthorized_handler
def unauthorized():
    session['after_login'] = request.url
    return redirect(url_for('user.login'))


@user_bp.route('/logout', methods=["GET", "POST"])
@login_required
def logout():
    logout_user()
    return redirect(url_for('products.index'))

app/templates/landing/_featured_stores.html
{% if stores %}
    <div class="container">
        <h3> Example stores </h3>
        <div class="row mt-3">
            {% for store in stores[0:3] %}
                <div class="col-sm">
                    <div class="card">
                        <div class="card-body">
                            <h5 class="card-title">{{ store.name }}</h5>

                            <div class="card-subtitle">
                                {{ store.products | count }}
                                {{  'product' if (store.products | count) == 1 else 'products' }}
                            </div>
                        </div>
                        <div class="card-footer">
                            <a href="{{ url_for('store.show', store_id=store.id) }}" class="card-link btn btn-primary">
                                View {{ store.name | title  }}
                            </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endif %}

app/templates/landing/_value_prop.html
<div class="container">
    <div class="row mt-3">
        <div class="col-md-4 col-xs-12 feature-block">
            <i class="fa fa-cc-stripe feature-icon"></i>
            <div class="feature-text-block">
                <div class="feature-heading">Built in checkout</div>
                <div class="features-text-block">
                    Yumroad uses Stripe checkout to accept credit card payments from around the world
                </div>
            </div>
        </div>
        <div class="col-md-4 col-xs-12 feature-block">
            <i class="fa fa-dollar feature-icon"></i>
            <div class="feature-text-block">
                <div class="feature-heading">Free</div>
                <div class="features-text-block">
                    Yumroad offers a free plan for store owners to quickly sell products
                </div>
            </div>
        </div>
        <div class="col-md-4 col-xs-12 feature-block">
            <i class="fa fa-cloud feature-icon"></i>
            <div class="feature-text-block">
                <div class="feature-heading">API
                    <a class="badge badge-warning ml-1"> Coming Soon</a>
                </div>
                <div class="features-text-block">
                    An API for you to create, retrieve, and embed products on your own site.
                </div>
            </div>
        </div>
    </div>
</div>

app/templates/landing/index.html
{% extends "base_layout.html" %}

{% block custom_assets %}
    <link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    {% assets "landing_css" %}
        <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}" />
    {% endassets %}
{% endblock %}

{% block content %}
    <div class="row header mt-4 mb-4">
        <div class="col-sm-12">
            <div class="header-title">
                <h1>The easiest way to setup an online store</h1>
                <div class="header-description mb-4">
                    Start selling your items in 30 seconds. Free for a limited time.
                </div>
                <div class="header-cta">
                    <a href="{{ url_for('store.index') }}" class="btn btn-primary">Browse Stores</a>
                    {% if not current_user.is_authenticated %}
                        <a href="{{ url_for('user.register') }}" class="btn btn-success">Create a store</a>
                    {% else %}
                        <a href="{{ url_for('products.create') }}" class="btn btn-success">Create a product</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <div class="row mb-4">
        {% include 'landing/_value_prop.html' %}
    </div>

    <div class="row mb-4">
        {% include 'landing/_featured_stores.html' %}
    </div>
{% endblock %}