app/blueprints/landing.py
from flask import Blueprint, render_template
import logging

from flask_login import current_user
from sqlalchemy.orm import joinedload

from app.extensions import cache
from app.models import Store

logger = logging.getLogger(__name__)

landing_bp = Blueprint('landing', __name__)


@landing_bp.route('/')
@cache.cached(timeout=60, unless=lambda: current_user.is_authenticated)
def index():
    # This is a bad query, we'll optimize it later
    stores = Store.query.options(
        joinedload(Store.products)
    ).limit(3).all()
    return render_template('landing/index.html', stores=stores)


@landing_bp.route('/error')
def error():
    logger.warning("About to do a dangerous calculation", extra={'data': 1})
    1/0

app/blueprints/products.py
from flask import Blueprint, render_template, request, url_for, flash
from flask_login import login_required, current_user
from werkzeug.exceptions import abort
from werkzeug.utils import redirect

from app.extensions import db, checkout
from app.forms import ProductForm
from app.models import Product

products = Blueprint('products', __name__)


@products.route('/')
def index():
    all_products = Product.query.all()
    return render_template('products/index.html', products=all_products)


@products.route('/<int:product_id>')
def details(product_id):
    product = Product.query.get_or_404(product_id)

    stripe_publishable_key = checkout.publishable_key
    stripe_session = checkout.create_session(product) or {}
    checkout_session_id = stripe_session.get('id')

    return render_template('products/details.html',
                           product=product,
                           stripe_publishable_key=stripe_publishable_key,
                           checkout_session_id=checkout_session_id)


@products.route('/<product_id>/post-checkout')
def post_checkout(product_id):
    product = Product.query.get_or_404(product_id)
    purchase_state = request.args.get('status')
    post_purchase_session_id = request.args.get('session_id')

    if purchase_state == 'success' and post_purchase_session_id:
        flash("Thanks for purchasing {}. You will receive an email shortly".format(product.name), 'success')
    elif purchase_state == 'cancel' and post_purchase_session_id:
        flash("There was an error while attempting to purchase this product. Try again", 'danger')

    return redirect(url_for('products.details', product_id=product_id))


@products.route('/create', methods=['GET', 'POST'])
@login_required
def create():
    form = ProductForm()
    if form.validate_on_submit():
        price = form.price.data or 0
        product = Product(name=form.name.data,
                          description=form.description.data,
                          price_cents=int(price*100),
                          picture_url=form.picture_url.data,
                          creator=current_user,
                          store=current_user.store)
        db.session.add(product)
        db.session.commit()

        return redirect(url_for('products.details', product_id=product.id))
    return render_template('products/create.html', form=form)


@products.route('/<product_id>/edit', methods=['GET', 'POST'])
@login_required
def edit(product_id):
    product = Product.query.get_or_404(product_id)
    form = ProductForm(obj=product)
    if form.validate_on_submit():
        product.name = form.name.data
        product.description = form.description.data
        db.session.add(product)
        db.session.commit()
        return redirect(url_for('.details', product_id=product.id))
    return render_template('products/edit.html', form=form, product=product)

app/blueprints/users.py
from flask import Blueprint, render_template, redirect, url_for, flash, session, request
from flask_login import login_user, login_required, logout_user, current_user

from app.email import send_pretty_welcome_message
from app.extensions import login_manager
from app.models import User, db, Store
from app.forms import SignupForm, LoginForm

user_bp = Blueprint('user', __name__)


@user_bp.route('/register', methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        flash("You are already logged in", 'warning')
        return redirect(url_for("products.index"))

    form = SignupForm()
    if form.validate_on_submit():
        user = User.create(form.email.data, form.password.data)
        store = Store(name=form.store_name.data, user=user)
        db.session.add(store)
        db.session.commit()

        login_user(user)
        send_pretty_welcome_message(user)

        flash("Registered succesfully.", "success")
        return redirect(session.get('after_login') or url_for("products.index"))
    return render_template("users/register.html", form=form)


@user_bp.route('/login', methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        flash("You are already logged in", 'warning')
        return redirect(url_for("products.index"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        login_user(user)
        flash("Logged in successfully.", "success")
        return redirect(url_for("products.index"))

    return render_template("users/login.html", form=form)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(user_id)


@login_manager.unauthorized_handler
def unauthorized():
    session['after_login'] = request.url
    return redirect(url_for('user.login'))


@user_bp.route('/logout', methods=["GET", "POST"])
@login_required
def logout():
    logout_user()
    return redirect(url_for('products.index'))

app/templates/_formhelpers.html
{% macro render_field(field) %}
    <div class="form-group {% if field.errors %} has-error{% endif -%} {%- if field.flags.required %} required{% endif -%}">
        <!--Label-->
        <label for="{{ field.name }}">{{ field.label }}</label>

        <!--Description-->
        {% if field.description %}
        <small classname="text-muted" for="{{ field.name }}">({{ field.description }})</small>
        {% endif %}

        <!--Input-->
        {{ field(class_=' '.join(['form-control', 'is-invalid' if field.errors else '']), **kwargs)|safe }}

        <!--Error List-->
        <ul class="invalid-feedback errors">
            {% for error in field.errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    </div>
{% endmacro %}

app/templates/_macros.html
{% macro render_flashes() %}
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <div class="container mt-4">
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        </button>
                        {{ message }}
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    {% endwith %}
{% endmacro %}

app/templates/_navbar.html
<nav class="navbar navbar-light bg-light justify-content-between">
    <div class="navbar-item">
        <a href="{{ url_for('landing.index') }}" class="navbar-brand">YumYum</a>
    </div>
    <div class="navbar-item form-inline">
        {% if current_user.is_authenticated %}
            <a href="{{ url_for('products.create') }}" class="navbar-link">
                Add Product
            </a>
            <a class="ml-3 navbar-link">{{ current_user.email }}</a>
            <a class="nav-link" href="{{ url_for('user.logout') }}">Log out</a>
        {% else %}
            <a class="nav-link" href="{{ url_for('user.register') }}">Register</a>
            <a class="nav-link" href="{{ url_for('user.login') }}">Login</a>
        {% endif %}
    </div>
</nav>

app/templates/base_layout.html
<!DOCTYPE html>
<html>
<head>
    <title>
    {% block title %}{% endblock %} Yumroad
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    {% assets "common_css" %}
        <link rel="stylesheet" type="text/css" href="{{ ASSET_URL }}" />
    {% endassets %}
    {% block custom_assets %} {% endblock %}
</head>
<body>
    {% from '_macros.html' import render_flashes %}

    {% include '_navbar.html' %}

    {{ render_flashes() }}

    <div class="container mt-3">
    {% block content %}{% endblock %}
    </div>
</body>
</html>